displayName=Mouse Tracker
author=Vincent0955
support=https://github.com/vincent0955/Visual-metronome
description=TEST TEST TEST
tags=timers, overlays, tick, skilling
plugins=com.visualmetronome.VisualMetronomePlugin
